name: Build FAA tiles and publish to B2 (pan-able, no region)

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  process-charts:
    runs-on: ubuntu-latest

    # Run everything inside the chartmaker image
    container:
      image: n129bz/chartmaker:latest

    strategy:
      fail-fast: false
      matrix:
        chart_type:
          # VFR sectionals = all sectional areas
          - { id: vfr,      args: "area-all" }
          # IFR enroute low/high are indices 5 & 6 in the "full" list
          - { id: ifr_low,  args: "full-single=5" }
          - { id: ifr_high, args: "full-single=6" }

    env:
      WEBSERVERMODE: "false"                            # prevent webserver
      B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}     # target B2 bucket

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node & jq in container
        run: |
          set -euxo pipefail
          if ! command -v node >/dev/null 2>&1; then
            if command -v apt-get >/dev/null 2>&1; then
              apt-get update
              apt-get install -y curl ca-certificates gnupg jq
              mkdir -p /etc/apt/keyrings
              curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
              echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
              apt-get update && apt-get install -y nodejs
            elif command -v apk >/dev/null 2>&1; then
              apk add --no-cache nodejs-current npm jq
            else
              echo "Unsupported base image"; exit 1
            fi
          else
            (apt-get update && apt-get install -y jq) || true
          fi
          node -v
          jq --version

      - name: Force CI settings (no web; keep intermediate tiles)
        working-directory: /chartmaker
        run: |
          set -euxo pipefail
          jq '.settings.webservermode=false
              | .settings.opendefaultbrowser=false
              | .settings.cleanprocessfolders=false' settings.json > s && mv s settings.json
          jq '.settings | {webservermode, opendefaultbrowser, cleanprocessfolders, zoomrange, tileimagequality}' settings.json

      - name: Copy chartdates.json into container
        run: |
          set -euxo pipefail
          cp "$GITHUB_WORKSPACE/chartdates.json" /chartmaker/chartdates.json

      # ---------- B2 CLI setup (once per job) ----------
      - name: Install B2 CLI (v4.x)
        run: |
          set -euxo pipefail
          if ! command -v pip3 >/dev/null 2>&1; then
            apt-get update && apt-get install -y python3-pip
          fi
          pip3 install --upgrade "b2[full]" --break-system-packages

      - name: Configure B2 credentials
        env:
          B2_KEY_ID:  ${{ secrets.B2_KEY_ID }}
          B2_APP_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        run: |
          set -euxo pipefail
          b2 account authorize "${B2_KEY_ID}" "${B2_APP_KEY}"

      # ---------- Pick FAA date from MM-DD-YYYY list ----------
      - name: Select FAA chart date from chartdates.json
        id: pickdate
        working-directory: /chartmaker
        run: |
          set -euo pipefail
          mapfile -t RAW < <(jq -r '.ChartDates[]' chartdates.json)
          if [ "${#RAW[@]}" -eq 0 ]; then
            echo "No ChartDates[] entries found" >&2; exit 1
          fi

          DATES=()
          for d in "${RAW[@]}"; do
            if [[ "$d" =~ ^([0-1][0-9])-([0-3][0-9])-(20[0-9]{2})$ ]]; then
              mm="${BASH_REMATCH[1]}"; dd="${BASH_REMATCH[2]}"; yyyy="${BASH_REMATCH[3]}"
              iso="${yyyy}-${mm}-${dd}"
              if epoch=$(date -u -d "$iso" +%s 2>/dev/null); then
                DATES+=("$iso")
              fi
            fi
          done
          if [ "${#DATES[@]}" -eq 0 ]; then
            echo "No valid dates after normalization" >&2; exit 1
          fi

          IFS=$'\n' read -r -d '' -a SORTED < <(printf "%s\n" "${DATES[@]}" | sort && printf '\0')
          TODAY_EPOCH="$(date -u +%s)"
          PREV=""; NEXT=""

          for iso in "${SORTED[@]}"; do
            epoch=$(date -u -d "$iso" +%s)
            if [ "$epoch" -le "$TODAY_EPOCH" ]; then
              PREV="$iso"
            else
              if [ -z "$NEXT" ]; then NEXT="$iso"; fi
            fi
          done

          if [ -n "$PREV" ]; then TARGET="$PREV"; else TARGET="$NEXT"; fi
          if [ -z "${TARGET:-}" ]; then
            echo "Could not determine target date" >&2; exit 1
          fi
          echo "target_date=$TARGET" >> "$GITHUB_OUTPUT"
          echo "Selected FAA chart date: $TARGET (today=$(date -u +%Y-%m-%d))"

      # ---------- Check B2, skip if date already present ----------
      - name: Check B2 for existing tiles (skip if present)
        id: check_b2
        env:
          B2_BUCKET:  ${{ secrets.B2_BUCKET_NAME }}
          CHART_TYPE: ${{ matrix.chart_type.id }}
          TARGET_DATE: ${{ steps.pickdate.outputs.target_date }}
        run: |
          set -euo pipefail
          PREFIX="tiles/${CHART_TYPE}/${TARGET_DATE}/"
          echo "Checking bucket: ${B2_BUCKET}"
          echo "Folder/prefix:   ${PREFIX}"

          OUT="$(b2 ls --json "${B2_BUCKET}" "${PREFIX}" 2>/dev/null || true)"
          echo "Raw b2 ls output (first 200 chars):"
          echo "${OUT}" | head -c 200; echo

          if echo "${OUT}" | jq -e 'type == "array" and length > 0' >/dev/null 2>&1; then
            COUNT=$(echo "${OUT}" | jq 'length')
            echo "Found ${COUNT} objects under ${PREFIX}"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "No objects found under ${PREFIX}"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      # ---------- Patch IFR High shapefile pattern (l->h) ----------
      - name: Fix IFR High clipshape filenames (create l* aliases for all h*)
        if: matrix.chart_type.id == 'ifr_high'
        working-directory: /chartmaker/clipshapes/enroute_high
        run: |
          set -euxo pipefail
          echo "Before aliasing:"
          ls -1 || true

          shopt -s nullglob
          made_any=0
          for shp in enr_h*.shp; do
            base="${shp%.shp}"         # e.g., enr_h36
            num="${base#enr_h}"        # e.g., 36
            dst="enr_l${num}"          # e.g., enr_l36
            for ext in shp shx dbf prj; do
              if [ -f "${base}.${ext}" ] && [ ! -e "${dst}.${ext}" ]; then
                cp -f "${base}.${ext}" "${dst}.${ext}"
                made_any=1
              fi
            done
          done

          echo "After aliasing:"
          ls -1 || true

          if [ "$made_any" -eq 0 ]; then
            echo "No 'enr_h*.shp' files found to alias; directory contents:" >&2
            ls -la >&2 || true
            # don't exit hard—let the build try; but warn loudly
          fi

      # ---------- Build if needed ----------
      - name: Build charts for ${{ matrix.chart_type.id }}
        if: steps.check_b2.outputs.exists != 'true'
        working-directory: /chartmaker
        env:
          WEBSERVERMODE: "false"
        run: |
          set -euxo pipefail
          node make "${{ matrix.chart_type.args }}"

      # ---------- Collect tile roots from workarea ----------
      - name: Locate tile roots
        if: steps.check_b2.outputs.exists != 'true'
        id: tiles
        run: |
          set -euo pipefail
          ROOT="/chartmaker/workarea"
          test -d "$ROOT" || { echo "No workarea found"; exit 1; }

          # a tile root has children named 5,6,7... (zoom directories)
          mapfile -t TILE_ROOTS < <(find "$ROOT" -type d -maxdepth 3 -regex '.*/[0-9]+' -printf '%h\n' | sort -u)
          if [ ${#TILE_ROOTS[@]} -eq 0 ]; then
            echo "No tile folders detected in $ROOT" >&2; exit 1
          fi
          printf "%s\n" "${TILE_ROOTS[@]}" > /tmp/tile_roots.txt
          echo "tile_roots_file=/tmp/tile_roots.txt" >> "$GITHUB_OUTPUT"
          echo "Found ${#TILE_ROOTS[@]} tile roots (first 10):"
          head -10 /tmp/tile_roots.txt || true

      # ---------- Upload to B2 with valid v4 flags ----------
      - name: Upload tiles to B2 (no region in path)
        if: steps.check_b2.outputs.exists != 'true'
        env:
          TILE_ROOTS_FILE: ${{ steps.tiles.outputs.tile_roots_file }}
          B2_BUCKET:       ${{ secrets.B2_BUCKET_NAME }}
          CHART_TYPE:      ${{ matrix.chart_type.id }}
          TARGET_DATE:     ${{ steps.pickdate.outputs.target_date }}
        run: |
          set -euxo pipefail
          DEST="b2://${B2_BUCKET}/tiles/${CHART_TYPE}/${TARGET_DATE}/"
          echo "Destination: $DEST"

          # Show CLI version for future debugging
          b2 version || true
          echo "b2 sync help (first lines):"
          b2 sync -h | head -n 20 || true

          while IFS= read -r ROOT; do
            echo "Syncing $ROOT -> $DEST"
            # Portable flags: --no-progress and --threads are widely available
            b2 sync \
              --no-progress \
              --threads 16 \
              "$ROOT/" "$DEST"
          done < "$TILE_ROOTS_FILE"

          echo "${TARGET_DATE}" > "latest_${CHART_TYPE}.txt"
          b2 file upload --no-progress "${B2_BUCKET}" "latest_${CHART_TYPE}.txt" "latest_${CHART_TYPE}.txt"

      # ---------- Retain only newest two date folders per type ----------
      - name: Retain only last two dates in B2
        env:
          B2_BUCKET:  ${{ secrets.B2_BUCKET_NAME }}
          CHART_TYPE: ${{ matrix.chart_type.id }}
        run: |
          set -euxo pipefail
          PREFIX="tiles/${CHART_TYPE}/"
          mapfile -t DATES < <(
            b2 ls "b2://${B2_BUCKET}/${PREFIX}" --json \
              | jq -r '.[].fileName' \
              | awk -v p="$PREFIX" -F'/' 'index($0,p)==1 {print $2}' \
              | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' \
              | sort -u
          )
          if [ ${#DATES[@]} -le 2 ]; then
            echo "Nothing to prune (dates found: ${DATES[*]:-none})"; exit 0
          fi
          KEEP1="${DATES[-1]}"; KEEP2="${DATES[-2]}"
          echo "Keeping: $KEEP2, $KEEP1"
          EMPTYDIR="$(mktemp -d)"
          for d in "${DATES[@]}"; do
            if [ "$d" != "$KEEP1" ] && [ "$d" != "$KEEP2" ]; then
              echo "Pruning tiles/${CHART_TYPE}/${d}/"
              b2 sync --delete "$EMPTYDIR/" "b2://${B2_BUCKET}/tiles/${CHART_TYPE}/${d}/"
            fi
          done
          rmdir "$EMPTYDIR" || true

      # ---------- Purge Cloudflare ----------
      - name: Purge Cloudflare cache
        env:
          CF_ZONE_ID:   ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CF_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
          CF_API_KEY:   ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
          set -euxo pipefail
          curl -sS "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
            -H 'Content-Type: application/json' \
            -H "X-Auth-Email: ${CF_API_EMAIL}" \
            -H "X-Auth-Key: ${CF_API_KEY}" \
            -d '{"purge_everything":true}' \
            -w "\nHTTP Status: %{http_code}\n"

      # ---------- Report & cleanup ----------
      - name: Create processing report
        if: always()
        env:
          TARGET_DATE: ${{ steps.pickdate.outputs.target_date }}
          CHART_TYPE:  ${{ matrix.chart_type.id }}
        run: |
          set -euo pipefail
          REPORT="$GITHUB_WORKSPACE/report_${CHART_TYPE}.md"
          {
            echo "# Chart Processing Report (${CHART_TYPE})"
            echo
            echo "**UTC Now:** $(date -u)  "
            echo "**FAA Chart Date:** ${TARGET_DATE}  "
            echo "**Chart Type:** ${CHART_TYPE}  "
            echo
            echo "## Disk Usage"
            echo '```'
            df -h
            echo '```'
          } > "$REPORT"
          echo "Wrote $REPORT"

      - name: Upload report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: processing-report-${{ matrix.chart_type.id }}-${{ steps.pickdate.outputs.target_date }}
          path: report_${{ matrix.chart_type.id }}.md
          retention-days: 30

      - name: Cleanup
        if: always()
        run: |
          set +e
          rm -rf /chartmaker/workarea/* /chartmaker/chartcache/* 2>/dev/null || true
          echo "Cleanup completed"

  notify:
    needs: process-charts
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send notification
        run: |
          if [ "${{ needs.process-charts.result }}" = "success" ]; then
            echo "✅ All chart types processed and uploaded (or skipped if current)."
          else
            echo "❌ One or more chart types failed."
            echo "See: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi