name: Process Aviation Charts

on:
  workflow_dispatch:
    inputs:
      chart_type:
        description: 'Chart processing type'
        required: true
        type: choice
        options:
          - 'single_sectional'
          - 'all_sectionals'
          - 'all_ifr_low'
          - 'all_ifr_high'
          - 'full_vfr'
          - 'full_ifr'
          - 'complete'
        default: 'single_sectional'
  
  schedule:
    - cron: '0 2 */28 * *'

jobs:
  process-charts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          df -h
      
      - name: Checkout chartmaker repository
        uses: actions/checkout@v4
        with:
          repository: N129BZ/chartmaker
          path: chartmaker
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gdal-bin \
            python3-gdal \
            python3-pip \
            python3-pil \
            python3-requests \
            nodejs \
            npm \
            curl \
            unzip \
            sqlite3 \
            perl \
            libperl-dev \
            build-essential
          
          # Verify installations
          gdalinfo --version
          node --version
          npm --version
          python3 --version
      
      - name: Install Perl dependencies
        working-directory: chartmaker
        run: |
          # Make perlinstall script executable and run it
          chmod +x perlinstall.sh
          sudo ./perlinstall.sh
      
      - name: Install Node.js dependencies
        working-directory: chartmaker
        run: |
          npm install
      
      - name: Install Python dependencies
        run: |
          pip3 install --break-system-packages pillow requests
      
      - name: Setup chartmaker permissions
        working-directory: chartmaker
        run: |
          chmod +x mergetiles.pl mbutil/mb-util
          sudo ln -sf $(pwd)/mbutil/mb-util /usr/local/bin/mb-util
          mkdir -p workarea chartcache public/charts
      
      - name: Install B2 CLI
        run: |
          wget https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux
          chmod +x b2-linux
          sudo mv b2-linux /usr/local/bin/b2
          b2 version
      
      - name: Configure B2
        run: |
          b2 account authorize "${{ secrets.B2_KEY_ID }}" "${{ secrets.B2_APPLICATION_KEY }}"
          echo "✅ B2 authorization successful"
          b2 account get
      
      - name: Determine chart command
        id: chart_command
        run: |
          CHART_TYPE="${{ github.event.inputs.chart_type }}"
          
          if [ -z "$CHART_TYPE" ]; then
            CHART_TYPE="single_sectional"
          fi
          
          case "$CHART_TYPE" in
            "single_sectional")
              COMMAND="area-single=12"
              echo "Processing single sectional: Dallas-Ft Worth (index 12)"
              ;;
            "all_sectionals")
              COMMAND="area=vfr"
              echo "Processing all VFR sectional charts"
              ;;
            "all_ifr_low")
              COMMAND="area=ifr-low"
              echo "Processing all IFR Low Enroute charts"
              ;;
            "all_ifr_high")
              COMMAND="area=ifr-high"
              echo "Processing all IFR High Enroute charts"
              ;;
            "full_vfr")
              COMMAND="all-vfr"
              echo "Processing all VFR charts"
              ;;
            "full_ifr")
              COMMAND="all-ifr"
              echo "Processing all IFR charts"
              ;;
            "complete")
              COMMAND=""
              echo "Processing ALL charts"
              ;;
            *)
              echo "Unknown chart type: $CHART_TYPE"
              exit 1
              ;;
          esac
          
          echo "command=$COMMAND" >> $GITHUB_OUTPUT
          echo "Chart command: '$COMMAND'"
      
      - name: Process charts
        working-directory: chartmaker
        run: |
          COMMAND="${{ steps.chart_command.outputs.command }}"
          
          echo "============================================"
          echo "Starting chart processing"
          echo "Command: '$COMMAND'"
          echo "Working directory: $(pwd)"
          echo "Processor count: $(nproc)"
          echo "============================================"
          
          # Run chartmaker directly
          if [ -z "${{ steps.chart_command.outputs.command }}" ]; then
            echo "No command specified, processing all charts"
            node make.js
          else
            echo "Processing with command: $COMMAND"
            node make.js $COMMAND
          fi
          
          echo "============================================"
          echo "Chart processing completed"
          echo "Output directory contents:"
          ls -lh public/charts/ || echo "No charts directory found"
          echo "============================================"
      
      - name: Get chart date
        working-directory: chartmaker
        id: chart_date
        run: |
          if [ ! -d "public/charts" ]; then
            echo "ERROR: public/charts directory doesn't exist"
            exit 1
          fi
          
          CHART_DATE=$(ls -t public/charts/ 2>/dev/null | head -n 1)
          
          if [ -z "$CHART_DATE" ]; then
            echo "ERROR: No chart directory found in public/charts/"
            echo "Directory contents:"
            ls -la public/charts/ || echo "Directory is empty"
            exit 1
          fi
          
          echo "chart_date=$CHART_DATE" >> $GITHUB_OUTPUT
          echo "Charts processed for date: $CHART_DATE"
      
      - name: Validate charts
        working-directory: chartmaker
        run: |
          CHART_DATE="${{ steps.chart_date.outputs.chart_date }}"
          
          echo "Validating charts in: public/charts/$CHART_DATE"
          
          if [ ! -d "public/charts/$CHART_DATE" ]; then
            echo "ERROR: Chart directory not found: public/charts/$CHART_DATE"
            exit 1
          fi
          
          FILE_COUNT=$(find public/charts/$CHART_DATE -type f 2>/dev/null | wc -l)
          echo "Found $FILE_COUNT files"
          
          if [ "$FILE_COUNT" -eq 0 ]; then
            echo "ERROR: No files generated in public/charts/$CHART_DATE"
            echo "Directory structure:"
            ls -laR public/charts/
            exit 1
          fi
          
          TOTAL_SIZE=$(du -sh public/charts/$CHART_DATE | cut -f1)
          
          echo "============================================"
          echo "✅ Validation passed!"
          echo "   Chart date: $CHART_DATE"
          echo "   Files: $FILE_COUNT"
          echo "   Total size: $TOTAL_SIZE"
          echo "============================================"
      
      - name: Upload to Backblaze
        working-directory: chartmaker
        env:
          B2_BUCKET: ${{ secrets.B2_BUCKET }}
        run: |
          CHART_DATE="${{ steps.chart_date.outputs.chart_date }}"
          
          echo "============================================"
          echo "Uploading to Backblaze B2"
          echo "Source: public/charts/$CHART_DATE"
          echo "Destination: b2://$B2_BUCKET/$CHART_DATE"
          echo "============================================"
          
          b2 sync --no-progress --threads 8 \
            public/charts/$CHART_DATE \
            b2://$B2_BUCKET/$CHART_DATE
          
          echo "✅ Upload completed successfully"
      
      - name: Purge Cloudflare cache
        if: success()
        run: |
          if [ -n "${{ secrets.CLOUDFLARE_ZONE_ID }}" ] && [ -n "${{ secrets.CLOUDFLARE_API_KEY }}" ]; then
            echo "Purging Cloudflare cache..."
            
            RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
              -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_API_EMAIL }}" \
              -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_API_KEY }}" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}')
            
            echo "Response: $RESPONSE"
            
            if echo "$RESPONSE" | grep -q '"success":true'; then
              echo "✅ Cloudflare cache purged successfully"
            else
              echo "⚠️ Cloudflare cache purge may have failed"
            fi
          else
            echo "⚠️ Cloudflare credentials not configured, skipping cache purge"
          fi
      
      - name: Summary
        if: success()
        run: |
          CHART_DATE="${{ steps.chart_date.outputs.chart_date }}"
          
          echo "============================================"
          echo "🎉 Chart Processing Complete!"
          echo "============================================"
          echo "Chart date: $CHART_DATE"
          echo "B2 bucket: ${{ secrets.B2_BUCKET }}"
          echo "Cloudflare URL: https://charts.leonis85.com/$CHART_DATE/"
          echo ""
          echo "Test a tile:"
          echo "https://charts.leonis85.com/$CHART_DATE/9/121/194.png"
          echo "============================================"
      
      - name: Cleanup
        if: always()
        working-directory: chartmaker
        run: |
          echo "Cleaning up work directories..."
          rm -rf workarea/* chartcache/* || true
          echo "✅ Cleanup completed"
          df -h